### ISSUE TITLE
Issue with notation-fonts/__init__.ily

### ISSUE THREAD

**Issue by JoeiGraph** [openlilylib/notation-fonts#12]
Hi Urs, as per request - sorry, I can't condense this issue more..

I'm trying to change the music font according to the descrition on github: https://github.com/openlilylib/notation-fonts

Whith this source code:

\version "2.19.58"

\include "oll-core/package.ily"
\loadPackage notation-fonts

\useNotationFont "beethoven"

\relative c' {
  c8 d e f g a b c
  c, e g r d f a r
}

I get this log and now result:
Starte lilypond-windows.exe 2.19.58 [example.ly]...
»C:/Users/Johannes/AppData/Local/Temp/frescobaldi-b939qq8v/tmpcg17kub8/example.ly« wird verarbeitet
Analysieren...
C:/Users/Johannes/OLL/notation-fonts/__init__.ily:81:2: Fehler: GUILE signalisierte einen Fehler für den hier beginnenden Ausdruck
#
 (let*
C:/Users/Johannes/AppData/Local/Temp/frescobaldi-b939qq8v/tmpcg17kub8/example.ly:6:1: Warnung: 

Trying to access non-existent option: global.installed-fonts.otf

\useNotationFont "beethoven"

Unbound variable: os-path-join-unix
C:/Users/Johannes/OLL/notation-fonts/package.ily:102:12: In procedure member in _expression_ (member use-name (#<procedure embedded-lilypond #> " \\getChildOption global.installed-fonts
                #(cond
                  ((eq? 'svg (ly:get-option 'backend))
                   'svg)
                  ((eq? 'svg-woff (ly:get-option 'backend))
                   'woff)
                  (else 'otf))
             " "C:/Users/Johannes/OLL/notation-fonts/package.ily" ...)):
C:/Users/Johannes/OLL/notation-fonts/package.ily:102:12: Wrong type argument in position 2: #f
Wurde mit dem Return-Code 1 beendet.

Cheers, Joei

**Comment by uliska** [comment]
Fixed with https://github.com/openlilylib/notation-fonts/pull/11

Please pull again and you should be good to go.
