### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by mrtnnbr** [openlilylib/notation-fonts#7]
Since the version predicates in oll-core are deprecated, using an alternative font spits out a warning. As it would only affect those using versions between 2.19.12 and 2.19.21, there might not be much of an impact if the check would just be dropped. (I made that change locally because I'm not in that demographic and was more annoyed by the warning.)

Any opinions?

**Comment by uliska** [comment]
I've noticed that too, and I'll remove that later today.
